# Static build version - changing the version dynamically means you can't
# just click from github to see how things are progressing until the build has
# finished, which could be a bit annoying.
version: 1.{build}-{branch}

environment:
  matrix:
  - platform: Win32
    target: Release
    visualstudio_string: vs2019
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  - platform: x64
    target: Release
    visualstudio_string: vs2019
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  - platform: ARM64
    target: Release
    visualstudio_string: vs2019
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

matrix:
  fast_finish: true

init:
# Use CRLF line endings on Windows so users can just use Notepad.
  - git config --global core.autocrlf true

install:
  - git submodule update --init --recursive

build_script:
  - msbuild VGMTrans_WTL.sln /m /p:BuildInParallel=true /p:Configuration=%target% /p:Platform=%platform% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - ps: $env:gitrev = git describe --always
  - ps: $env:my_version = "$env:gitrev-$env:appveyor_repo_branch-$env:appveyor_build_number"
  - set package_name=vgmtrans-%my_version%--%platform%-%target%
  - copy %target%\VGMTrans_WTL.exe bin\vgmtrans.exe || copy %platform%\%target%\VGMTrans_WTL.exe bin\vgmtrans.exe
  - mkdir vgmtrans
  - move bin vgmtrans
  - move LICENSE.txt vgmtrans
  - move README.md vgmtrans
  - 7z a -mx9 %package_name%.7z vgmtrans

test: off

artifacts:
  - path: $(package_name).7z
    name: $(visualstudio_string)-$(target)-$(platform)
